### ISSUE TITLE
Making the Welcome/Intro speech/talk even better!

### ISSUE THREAD

**Issue by zakkak** [devstaff-crete/DevStaff-Heraklion#225] opened 2018-03-07 23:29 UTC
A few of us (mostly old members I guess) are becoming a bit tired of the welcome slides and talk.

The aim of this issue is to start a discussion on how we could reduce the time it takes to introduce devstaff to newcomers to avoid tiring the old members, that usually are the majority.

A simple starting point would be to ask if there is someone new in the room, if not then we can totally skip the intro.

Now if there is even one newcomer in the room I believe we should make a small intro about the meetup.

Now for a newcomer to appear I assume (s)he learned about the meetup in one of the following ways: 
1. Through meetup.com
2. Someone told him/her about this cool event
3. Are we using social media to promote the events?

Now in the first case, it means (s)he had access to the meetup.com page of our meetup and probably went through the info given there.

In the second case, probably the person that introduced it to the newcomer mentioned a few thinks about how the whole think works.

That said, I believe that no newcomer comes without prior knowledge to an event. As a result we could reduce the info given during the event.

I believe the most important thing to do is to give pointers and not spoon feed them. This is a community for devs, devs should know how to RTFM!
The pointers should be:
1. the meetup.com page
2. the slack url
3. https://github.com/devstaff-crete/DevStaff-Heraklion
4. https://github.com/devstaff-crete/DevStaff-Heraklion/blob/master/StartHere.md

Put those in a slide, shortly tell them what each of them is and give them time to take a picture and we are done ;)

Let the fight begin!!!

**Comment by sonaht** [comment] 2018-03-08 08:34
![score_1_0_forum](https://user-images.githubusercontent.com/1314645/37140989-4e770e18-22bc-11e8-880f-64a005f9a10d.png)

**Comment by gsaslis** [comment] 2018-03-11 22:37
> The aim of this issue is to start a discussion on how we could reduce the time it takes to introduce devstaff to newcomers to avoid tiring the old members, that usually are the majority.

To be perfectly honest with you, this is not a discussion I would like to contribute to (or even participate in). I believe in open, inclusive communities where even minorities should be made to feel welcome (yes, at the expense of the majority).

**Comment by zakkak** [comment] 2018-03-11 23:29
I don't see why a more efficient intro would make someone feel less welcome.

I am talking about optimizing the process and not deprecating it. I personally believe that we can achieve the same goal in less time. One would even argue that 10-15 minutes are not enough and one should have an intro that lasts 30 minutes.

PS: If the issue is my intro (talking about minorities and majorities), please ignore it and let's discuss whether we can achieve a shorter yet complete introduction.

**Comment by papas-source** [comment] 2018-03-12 12:16
I also don't see why the minority would not feel welcome if the intro was a little bit shorter in time!

The issue here is not whether the old or new members would feel tired or "not welcome". The issue is to optimize the schedule so we dont have to spend half an hour everytime in order to introduce new members to the devstaff (hint: By their presence, the certain thing is they already know)!

I believe that @zakkak is absolutely right on his observations with the three points. 

> Now for a newcomer to appear I assume (s)he learned about the meetup in one of the following ways:
> 
> 1. Through meetup.com
> 2. Someone told him/her about this cool event
> 3. Are we using social media to promote the events?
> 
> Now in the first case, it means (s)he had access to the meetup.com page of our meetup and probably went through the info given there.
> 
> In the second case, probably the person that introduced it to the newcomer mentioned a few thinks about how the whole think works.
> 
> That said, I believe that no newcomer comes without prior knowledge to an event. As a result we could reduce the info given during the event.

Anyway, I believe that an intro is required. 
What we want to do, is optimize this intro in order to
1. Dont bore to death the existing members (or make them think that they can join half an hour later in order to avoid the intro)
2. Let new members know about the community around devstaff. 


the (2) can be accomplished by describing with details all the devstaff-related-matters (github, slack, meetup) in each and every media announcement for events or any actions. 
For example, we post an event to facebook, and thats it! One has to search a lot in order to know exactly who/where/how all this thing adds up.

Detailed information about devstaff should be made available to each and every mention of event, org meetup, hack session in social media or anywhere. If these details exist, there is no need for an intro more than 5 minutes...

just my 2c

**Comment by papas-source** [comment] 2018-03-12 12:20
also, we should make a media kit.
Maybe a template that all announcements and social messages will abide to. 

For example, having the logo of devstaff on the upper right corner for every announcement and social message, will grow awareness about devstaff and make people accustomed to the "thing" behind all this.

**Comment by sksksksk** [comment] 2018-03-12 15:17
I think that the real issue is whether we want new members to feel actually welcome. 

Spending time to describe what we are, the available communication channels and how this thing works, provides the needed confidence that this is not some gathering of elite people looking down to the newcomers.

So, personally, I don't care about the 10 more minutes.

**Comment by zakkak** [comment] 2018-03-12 16:49
> Spending time to describe what we are, the available communication channels and how this thing works, provides the needed confidence that this is not some gathering of elite people looking down to the newcomers.

I don't believe that the duration of the intro is the one that defines how welcoming a community is.
There are much more important things than that, such as interacting with the newcomers during the breaks and after the talks, encouraging questions, avoiding assumptions about the level of understanding of the audience, etc.

**Comment by zakkak** [comment] 2018-03-12 16:53
Also note that if I was a newcomer @gsaslis' answer to this issue would have definitely made me feel unwelcome and discourage me from opening other issues in the future.

**Comment by kabitakis** [comment] 2018-03-12 17:30
The discussion here seems to be about an improvement on the introductory slides, not excluding the introductory section. Every suggested improvement should be welcome and there is no need to argue if anything should be improved. Everything should be constantly improving and adapting to the current needs.

So, improvements are welcome anytime, using a PR (pull request). Please do!

On the other hand I'd like to thank @gsaslis for his commitment to make this boring-for-him presentation every single time (almost) for 20+ consecutive times in order to keep everything clear and transparent and also provide a figure (himself) which a newcomer may feel easier to approach during a break.

Let's close this issue anytime soon and I suppose we'll be shortly able to review the related PRs.

**Comment by zakkak** [comment] 2018-03-12 17:57
> Let's close this issue anytime soon and I suppose we'll be shortly able to review the related PRs.

@kabitakis I am not sure how a PR for this issue should look like.

Nevertheless, to improve something you first need to identify what can be improved and whether what one might believe to be an improvement is actually an improvement.

In this case I believe that the intro takes longer than needed, so I opened this issue to initiate a discussion about it. In the process I mentioned how and why I believe this can be achieved.

Till now only two people have actually replied to the issue at hand, which is by no means a representative number of the community.

**Comment by papas-source** [comment] 2018-03-12 18:45
> On the other hand I'd like to thank @gsaslis for his commitment to make this boring-for-him presentation every single time (almost) for 20+ consecutive times in order to keep everything clear and transparent and also provide a figure (himself) which a newcomer may feel easier to approach during a break

I' ll second that with all my is! (με όλο μου το είναι). He definitely is kind of a father figure and not only his presentation but also the the way he talks and organizes everything, should be an inspiration to us all.

But it has nothing to do with the issue per se.

**Comment by kabitakis** [comment] 2018-03-13 08:10
I referred to gsaslis because in an open community the way you put anything is very important in order to keep committed members engaged. These people and their work might be the most valuable asset of a community. They are the reason an idea or an opinion was actually implemented.

Ideas and opinions, on the other hand, are not that important due to the law of supply and demand.

In order to keep first things first, we should thank @gsaslis for his efforts before we tell him he is boring to us and request a new approach. So, this issue has everything to do with that.

**Comment by papas-source** [comment] 2018-03-13 09:39
@kabitakis you miss the point, really.

And given that we made clear that it has nothing to do with George (in the contrary we value and appreciate his efforts), I cannot help but think that you didn't really understand what we are talking about.

> In order to keep first things first we should thank @gsaslis for his efforts before we tell him he is boring to us 

Nobody ever said or even implied that George bores as - as you state. But in order to be done with this, 

<3 thank you @gsaslis for your efforts, (as already stated) we much appreciate it!

So, once again. It has nothing to do with George. It is about optimizing a process to better serve us all. If you want to gather it as an attack to George, you are free to think so but be alarmed, this is not the case at all!

**Comment by estavrak** [comment] 2018-03-13 10:28
I sped up the intro in the previous meetup. Of the three peeps who were there for the first time, two approached me and asked for more info at the end of the session. I believe I should have pressed on about meetup.com and slack (what they are, how we use them).

On another note, I know that consistency is important in these kind of open communities. The intro serves three purposes at the moment:
1. Engages newcomers
2. Provide everyone with a brief moment to ask about, comment on or share something they think might be important enough. How many meetup issues have come up 
3. It is a has become steadfast part of the meetup. Something familiar that all members recognize, even though it is reviewed from time to time. That familiarity is important to make everyone more welcome and strengthens the informal relationships among members, consequently enabling networking.

We should keep it and continue improving it, not as a rigid monologue; but as welcome note to everyone, old members and new, and an ice breaking tool to get people relaxed and engaged.

**Comment by zakkak** [comment] 2018-04-18 10:37
At the last org-meetup we decided that the welcoming presentation could get better with a few modifications (such as the addition of QR codes, refactoring of slides, etc.). So anyone who feels like contributing/participating in this process please join #welcome-refactoring on slack

Additionally we concluded that it would be better if we had more than one people giving the welcome presentation so that we don't create the illusion that this person is the leader or whatever. So again, if you are interested in giving the welcome speech once in a while please let me know!

**Comment by sonaht** [comment] 2021-03-23 08:05
We have been making changes to the intro. Any further suggestions are totally welcomed. Either open a specific PR or join one of the org meetups to state your case.

Closing this

**Closed by sonaht** 2021-03-23 08:05 UTC
